// eslint-disable-next-line import/prefer-default-export
export const GET_ACCOUNT_HOLDERS = "GET_ACCOUNT_HOLDERS";
export const GET_TOTAL_ACCOUNT_HOLDERS = "GET_TOTAL_ACCOUNT_HOLDERS";
export const SET_ACCOUNT_HOLDER_CONTACT_LIST =
  "SET_ACCOUNT_HOLDER_CONTACT_LIST";
export const CLEAR_CONTACT_LIST = "CLEAR_CONTACT_LIST";
export const ADD_ACCOUNT_HOLDERS = "ADD_ACCOUNT_HOLDERS";
export const SET_IS_ACCOUNT_HOLDER = "SET_IS_ACCOUNT_HOLDER";
export const SET_PRIMARY_PERSON = "SET_PRIMARY_PERSON";
export const SET_SECONDARY_PERSON_ID = "SET_SECONDARY_PERSON_ID";
export const SET_IS_SECONDARY = "SET_IS_SECONDARY";
