/*
 * Copyright (c) 2015-2022, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from "axios";

// This file has been auto generated by the java class GenerateAxiosClient
const AutoloadAPI = (config) => {
  const {partnerEndpoint, ...others} = config;
  const instance = axios.create({
    baseURL: `${partnerEndpoint}/v1/customer-autoload`,
    ...others,
  });

  return {
    interceptors: instance.interceptors,
    // cancelAutoLoadRequest: (customerNumber, id) => instance.delete(`${customerNumber}/autoloadRequest/${id}`),
    createAutoLoadRule: (customerNumber, dto) => instance.post(`${customerNumber}/autoload-rules`, dto),
    updateAutoLoadRule: (customerNumber, dto) => instance.put(`${customerNumber}/autoload-rules`, dto),
    deleteAutoLoadRule: (customerNumber, ruleId) => instance.delete(`${customerNumber}/autoload-rules/${ruleId}`),
    // getAutoLoadRequests: (customerNumber) => instance.get(`${customerNumber}/autoloadRequests`),
    getAutoLoadRules: (customerNumber) => instance.get(`${customerNumber}/autoload-rules`),
  };
};

export default AutoloadAPI;
