/*
 * Copyright (c) 2015-2023, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */
import { setup } from "axios-cache-adapter";

// This file has been auto generated by the java class GenerateAxiosClient
const RiskAPI = (config: any) => {
  const { partnerEndpoint, ...others } = config;

  const instance = setup({
    baseURL: `${partnerEndpoint}/v1/programs/`,
    ...others,
  });

  return {
    interceptors: instance.interceptors,
    createRiskLevel: (programName: any, dto: any) =>
      instance.post(`${encodeURIComponent(programName)}/risk/levels`, dto),
    createUpdateRiskConfig: (programName: any, securityLevel: any, dto: any) =>
      instance.post(
        `${encodeURIComponent(
          programName
        )}/risk/levels/${securityLevel}/configs`,
        dto
      ),
    deleteRiskConfig: (programName: any, securityLevel: any, paramName: any) =>
      instance.delete(
        `${encodeURIComponent(
          programName
        )}/risk/levels/${securityLevel}/configs/${paramName}`
      ),
    deleteRiskLevel: (programName: any, securityLevel: any) =>
      instance.delete(
        `${encodeURIComponent(programName)}/risk/levels/${securityLevel}`
      ),
    getRiskConfig: (programName: any, securityLevel: any, paramName: any) =>
      instance.get(
        `${encodeURIComponent(
          programName
        )}/risk/levels/${securityLevel}/configs/${paramName}`
      ),
    getRiskConfigs: (programName: any, securityLevel: any) =>
      instance.get(
        `${encodeURIComponent(
          programName
        )}/risk/levels/${securityLevel}/configs`
      ),
    getRiskLevel: (programName: any, securityLevel: any) =>
      instance.get(
        `${encodeURIComponent(programName)}/risk/levels/${securityLevel}`
      ),
    getRiskLevels: (programName: any) =>
      instance.get(`${encodeURIComponent(programName)}/risk/levels`),
    getRiskParams: (programName: any) =>
      instance.get(`${encodeURIComponent(programName)}/risk/params`),
  };
};

export default RiskAPI;
