/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const BankAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/banks/`, ...others });

    return {
        interceptors: instance.interceptors,
        addBankAccount: (bankName, dto) => instance.post(`${bankName}/accounts`, dto),
        addIIN: (bankName, dto) => instance.post(`${bankName}/iins`, dto),
        create: dto => instance.post('', dto),
        get: bankName => instance.get(`${bankName}`),
        getCurrencies: bankName => instance.get(`${bankName}/currencies`),
        getIINs: bankName => instance.get(`${bankName}/iins`),
        list: () => instance.get(''),
        removeIIN: (bankName, iin) => instance.delete(`${bankName}/iin/${iin}`),
        supportedCurrencyList: () => instance.get('currencies'),
    };
};

export default BankAPI;
