/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const CustomerChangeOrderAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/customers/`, ...others });

    return {
        interceptors: instance.interceptors,
        approveChangeOrder: (customerIdentifier, changeOrderId, dto) => instance.post(`${customerIdentifier}/changeOrders/${changeOrderId}`, dto),
        // eslint-disable-next-line max-len
        createAdjustmentRequest: (customerIdentifier, changeOrderId, dto) => instance.post(`${customerIdentifier}/changeOrders/${changeOrderId}/adjustment`, dto),
        createChangeOrder: (customerIdentifier, dto) => instance.post(`${customerIdentifier}/changeOrders`, dto),
        // eslint-disable-next-line max-len
        discardAdjustmentRequest: (customerIdentifier, changeOrderId, changeRequestId, memo) => instance.delete(`${customerIdentifier}/changeOrders/${changeOrderId}/adjustment/${changeRequestId}`, { params: { memo } }),
        // eslint-disable-next-line max-len
        discardChangeOrder: (customerIdentifier, changeOrderId, memo) => instance.delete(`${customerIdentifier}/changeOrders/${changeOrderId}`, { params: { memo } }),
        getChangeOrder: (customerIdentifier, changeOrderId) => instance.get(`${customerIdentifier}/changeOrders/${changeOrderId}`),
        // eslint-disable-next-line object-curly-newline,max-len
        getChangeOrders: (customerIdentifier, { state, count, startIndex, ascending }) => instance.get(`${customerIdentifier}/changeOrders`, { params: { state, count, 'start-index': startIndex, ascending } }),
        // eslint-disable-next-line object-curly-newline,max-len
        getChangeOrdersByLinkedPartner: ({ partnerName, state, count, startIndex, ascending }) => instance.get('changeOrders', { params: { 'partner-name': partnerName, state, count, 'start-index': startIndex, ascending } }),
        // eslint-disable-next-line max-len
        getChangeRequest: (customerIdentifier, changeOrderId, changeRequestId) => instance.get(`${customerIdentifier}/changeOrders/${changeOrderId}/changeRequests/${changeRequestId}`),
        getChangeRequests: (customerIdentifier, changeOrderId) => instance.get(`${customerIdentifier}/changeOrders/${changeOrderId}/changeRequests`),
    };
};

export default CustomerChangeOrderAPI;
