/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const CustomerAttributeAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/customers/`, ...others });

    return {
        interceptors: instance.interceptors,
        createCustomerAttribute: (customerIdentifier, dto) => instance.post(`${customerIdentifier}/attrs`, dto),
        deleteCustomerAttribute: (customerIdentifier, customerAttrId) => instance.delete(`${customerIdentifier}/attrs/${customerAttrId}`),
        getCustomerAttribute: (customerIdentifier, customerAttrId) => instance.get(`${customerIdentifier}/attrs/${customerAttrId}`),
        getCustomerAttributes: customerIdentifier => instance.get(`${customerIdentifier}/attrs`),
        updateCustomerAttribute: (customerIdentifier, customerAttrId, dto) => instance.put(`${customerIdentifier}/attrs/${customerAttrId}`, dto),
    };
};

export default CustomerAttributeAPI;
