/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const MailTemplateAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/programs/`, ...others });

    return {
        interceptors: instance.interceptors,
        createMailTemplate: (programName, language, dto) => instance.post(`${programName}/mail/${language}/templates`, dto),
        createMailTemplateSet: (programName, dto) => instance.post(`${programName}/mail`, dto),
        // eslint-disable-next-line max-len
        deleteMailTemplate: (programName, language, mailTemplateId) => instance.delete(`${programName}/mail/${language}/templates/${mailTemplateId}`),
        deleteMailTemplateSet: (programName, language) => instance.delete(`${programName}/mail/${language}`),
        getMailTemplate: (programName, language, mailTemplateId) => instance.get(`${programName}/mail/${language}/templates/${mailTemplateId}`),
        getMailTemplateSet: (programName, language) => instance.get(`${programName}/mail/${language}`),
        getMailTemplateSets: programName => instance.get(`${programName}/mail`),
        getMailTemplates: (programName, language) => instance.get(`${programName}/mail/${language}/templates`),
    };
};

export default MailTemplateAPI;
