/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const MemoAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/programs/`, ...others });

    return {
        interceptors: instance.interceptors,
        createMemoTemplate: (programName, language, dto) => instance.post(`${programName}/memos/${language}/templates`, dto),
        createMemoTemplateSet: (programName, dto) => instance.post(`${programName}/memos`, dto),
        // eslint-disable-next-line max-len
        deleteMemoTemplate: (programName, language, memoTemplateId) => instance.delete(`${programName}/memos/${language}/templates/${memoTemplateId}`),
        deleteMemoTemplateSet: (programName, language) => instance.delete(`${programName}/memos/${language}`),
        getMemoTemplate: (programName, language, memoTemplateId) => instance.get(`${programName}/memos/${language}/templates/${memoTemplateId}`),
        getMemoTemplateSet: (programName, language) => instance.get(`${programName}/memos/${language}`),
        getMemoTemplateSets: programName => instance.get(`${programName}/memos`),
        getMemoTemplates: (programName, language) => instance.get(`${programName}/memos/${language}/templates`),
    };
};

export default MemoAPI;
