/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const OperatingAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/programs/`, ...others });

    return {
        interceptors: instance.interceptors,
        addExchange: (programName, exchangeName) => instance.post(`${programName}/exchanges/${exchangeName}`),
        create: dto => instance.post('', dto),
        createCustodialAccount: (programName, dto) => instance.post(`${programName}/custodial`, dto),
        get: programName => instance.get(`${programName}`),
        getCustodialPortfolioAccount: (programName, currency) => instance.get(`${programName}/custodial/${currency}`),
        getCustodialPortfolioAccountList: programName => instance.get(`${programName}/custodial`),
        getExchanges: programName => instance.get(`${programName}/exchanges`),
        getInvoice: (programName, invoiceId) => instance.get(`${programName}/invoices/${invoiceId}`),
        getInvoiceSummaries: (programName, invoiceId) => instance.get(`${programName}/invoices/${invoiceId}/summaries`),
        // eslint-disable-next-line max-len
        getInvoiceSummary: (programName, invoiceId, invoiceSummaryId) => instance.get(`${programName}/invoices/${invoiceId}/summaries/${invoiceSummaryId}`),
        // eslint-disable-next-line object-curly-newline,max-len
        getInvoices: (programName, currency, { state, count, startIndex, ascending }) => instance.get(`${programName}/custodial/${currency}/invoices`, { params: { state, count, 'start-index': startIndex, ascending } }),
        getProgramReport: programName => instance.get(`${programName}/report`),
        list: () => instance.get(''),
        // eslint-disable-next-line max-len
        listInvoices: (programName, { count, startIndex, ascending }) => instance.get(`${programName}/invoices`, { params: { count, 'start-index': startIndex, ascending } }),
        removeExchange: (programName, exchangeName) => instance.delete(`${programName}/exchanges/${exchangeName}`),
        // eslint-disable-next-line max-len
        updateInvoiceSummary: (programName, invoiceId, invoiceSummaryId, dto) => instance.post(`${programName}/invoices/${invoiceId}/summaries/${invoiceSummaryId}`, dto),
        updateProgramReport: (programName, dto) => instance.post(`${programName}/report`, dto),
    };
};

export default OperatingAPI;
