/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const OperatingChangeOrderAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/programs/`, ...others });

    return {
        interceptors: instance.interceptors,
        approveChangeOrder: (programName, changeOrderId, dto) => instance.post(`${programName}/changeOrders/${changeOrderId}`, dto),
        createChangeOrder: (programName, dto) => instance.post(`${programName}/changeOrders`, dto),
        // eslint-disable-next-line max-len
        createUpdateExchangeMarginRequest: (programName, changeOrderId, dto) => instance.post(`${programName}/changeOrders/${changeOrderId}/exchanges/margins`, dto),
        createUpdateFeeEntryRequest: (programName, changeOrderId, dto) => instance.post(`${programName}/changeOrders/${changeOrderId}/fees`, dto),
        createUpdateFeePlanRequest: (programName, changeOrderId, dto) => instance.post(`${programName}/changeOrders/${changeOrderId}/feeplans`, dto),
        // eslint-disable-next-line max-len
        createUpdateRiskConfigRequest: (programName, changeOrderId, dto) => instance.post(`${programName}/changeOrders/${changeOrderId}/risk/configs`, dto),
        // eslint-disable-next-line max-len
        createUpdateRiskLevelRequest: (programName, changeOrderId, dto) => instance.post(`${programName}/changeOrders/${changeOrderId}/risk/levels`, dto),
        // eslint-disable-next-line max-len
        discardChangeOrder: (programName, changeOrderId, memo) => instance.delete(`${programName}/changeOrders/${changeOrderId}`, { params: { memo } }),
        // eslint-disable-next-line max-len
        discardExchangeMarginRequest: (programName, changeOrderId, requestId, memo) => instance.delete(`${programName}/changeOrders/${changeOrderId}/exchanges/margins/${requestId}`, { params: { memo } }),
        // eslint-disable-next-line max-len
        discardFeeEntry: (programName, changeOrderId, requestId, memo) => instance.delete(`${programName}/changeOrders/${changeOrderId}/fees/${requestId}`, { params: { memo } }),
        // eslint-disable-next-line max-len
        discardFeePlanRequest: (programName, changeOrderId, requestId, memo) => instance.delete(`${programName}/changeOrders/${changeOrderId}/feeplans/${requestId}`, { params: { memo } }),
        // eslint-disable-next-line max-len
        discardRiskConfigRequest: (programName, changeOrderId, requestId, memo) => instance.delete(`${programName}/changeOrders/${changeOrderId}/risk/configs/${requestId}`, { params: { memo } }),
        // eslint-disable-next-line max-len
        discardRiskLevelRequest: (programName, changeOrderId, requestId, memo) => instance.delete(`${programName}/changeOrders/${changeOrderId}/risk/levels/${requestId}`, { params: { memo } }),
        getChangeOrder: (programName, changeOrderId) => instance.get(`${programName}/changeOrders/${changeOrderId}`),
        // eslint-disable-next-line object-curly-newline,max-len
        getChangeOrders: (programName, { state, count, startIndex, ascending }) => instance.get(`${programName}/changeOrders`, { params: { state, count, 'start-index': startIndex, ascending } }),
        // eslint-disable-next-line object-curly-newline,max-len
        getChangeOrdersByProgram: ({ programName, state, count, startIndex, ascending }) => instance.get('changeOrders', { params: { 'program-name': programName, state, count, 'start-index': startIndex, ascending } }),
        // eslint-disable-next-line max-len
        getChangeRequest: (programName, changeOrderId, changeRequestId) => instance.get(`${programName}/changeOrders/${changeOrderId}/changeRequests/${changeRequestId}`),
        getChangeRequests: (programName, changeOrderId) => instance.get(`${programName}/changeOrders/${changeOrderId}/changeRequests`),
    };
};

export default OperatingChangeOrderAPI;
