/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const PartnerFeesAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/partner-programs/`, ...others });

    return {
        interceptors: instance.interceptors,
        createOrUpdate: (programName, dto) => instance.post(`${programName}/fees`, dto),
        delete: (programName, feeEntryId) => instance.delete(`${programName}/fees/${feeEntryId}`),
        getFee: (programName, feeEntryId) => instance.get(`${programName}/fees/${feeEntryId}`),
        // eslint-disable-next-line max-len
        getFees: (programName, { currency, transactionSource, transactionType }) => instance.get(`${programName}/fees`, { params: { currency, 'transaction-source': transactionSource, 'transaction-type': transactionType } }),
        getPartnerFeeEntries: () => instance.get('fees'),
    };
};

export default PartnerFeesAPI;
