/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const PersonAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/persons/`, ...others });

    return {
        interceptors: instance.interceptors,
        deleteAddress: (personId, addressId) => instance.delete(`${personId}/addresses/${addressId}`),
        deleteEmail: (personId, emailId) => instance.delete(`${personId}/emails/${emailId}`),
        deletePhone: (personId, phoneId) => instance.delete(`${personId}/phones/${phoneId}`),
        get: personId => instance.get(`${personId}`),
        getAddress: (personId, addressId) => instance.get(`${personId}/addresses/${addressId}`),
        getAddressHistory: personId => instance.get(`${personId}/addresses/history`),
        getAddressList: (personId, type) => instance.get(`${personId}/addresses`, { params: { type } }),
        getEmail: (personId, emailId) => instance.get(`${personId}/emails/${emailId}`),
        getEmailHistory: personId => instance.get(`${personId}/emails/history`),
        getEmailList: (personId, type) => instance.get(`${personId}/emails`, { params: { type } }),
        getOfficialId: (personId, officialId) => instance.get(`${personId}/officialIds/${officialId}`),
        getOfficialIdHistory: (personId, type) => instance.get(`${personId}/officialIds/history`, { params: { type } }),
        getOfficialIds: (personId, type) => instance.get(`${personId}/officialIds`, { params: { type } }),
        getPersonHistory: personId => instance.get(`${personId}/person/history`),
        getPersonHistoryAtTime: (personId, time) => instance.get(`${personId}/person/history/${time}`),
        getPhone: (personId, phoneId) => instance.get(`${personId}/phones/${phoneId}`),
        getPhoneHistory: personId => instance.get(`${personId}/phones/history`),
        getPhoneList: (personId, type) => instance.get(`${personId}/phones`, { params: { type } }),
        update: (personId, dto) => instance.post(`${personId}`, dto),
        updateAddress: (personId, dto) => instance.post(`${personId}/addresses`, dto),
        updateEmail: (personId, dto) => instance.post(`${personId}/emails`, dto),
        updateOfficialId: (personId, dto) => instance.post(`${personId}/officialIds`, dto),
        updatePhone: (personId, dto) => instance.post(`${personId}/phones`, dto),
    };
};

export default PersonAPI;
