/*
 * Copyright (c) 2015-2021, Episode Six and/or its affiliates. All rights reserved.
 * EPISODE SIX PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * THIS IS CONFIDENTIAL AND PROPRIETARY TO EPISODE SIX, and any
 * copying, reproduction, redistribution, dissemination, modification, or
 * other use, in whole or in part, is strictly prohibited without the prior
 * written consent of (or as may be specifically permitted in a fully signed
 * agreement with) Episode Six.   Violations may result in severe civil and/or
 * criminal penalties, and Episode Six will enforce its rights to the maximum
 * extent permitted by law.
 */

import axios from 'axios';


// This file has been auto generated by the java class GenerateAxiosClient
const RiskAPI = (config) => {
    const { baseURL, ...others } = config;
    const instance = axios.create({ baseURL: `${baseURL}/v1/programs/`, ...others });

    return {
        interceptors: instance.interceptors,
        createRiskLevel: (programName, dto) => instance.post(`${programName}/risk/levels`, dto),
        createUpdateRiskConfig: (programName, securityLevel, dto) => instance.post(`${programName}/risk/levels/${securityLevel}/configs`, dto),
        // eslint-disable-next-line max-len
        deleteRiskConfig: (programName, securityLevel, paramName) => instance.delete(`${programName}/risk/levels/${securityLevel}/configs/${paramName}`),
        deleteRiskLevel: (programName, securityLevel) => instance.delete(`${programName}/risk/levels/${securityLevel}`),
        getRiskConfig: (programName, securityLevel, paramName) => instance.get(`${programName}/risk/levels/${securityLevel}/configs/${paramName}`),
        getRiskConfigs: (programName, securityLevel) => instance.get(`${programName}/risk/levels/${securityLevel}/configs`),
        getRiskLevel: (programName, securityLevel) => instance.get(`${programName}/risk/levels/${securityLevel}`),
        getRiskLevels: programName => instance.get(`${programName}/risk/levels`),
        getRiskParams: programName => instance.get(`${programName}/risk/params`),
    };
};

export default RiskAPI;
